[build-system]
requires = [
    "setuptools>=69.0.3",
    "wheel",
]
build-backed = "setuptools.build_meta"


[tool.pytest.ini_options]
addopts = [
    "-ra",
    "--cov=robolot",
]

testpaths = [
    "tests",
]